language: java
dist: trusty
jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.m2/repository"
env:
  global:
    - JAVA_TOOL_OPTIONS=-Xmx3g java -version
    - ORG="devonfw"
    - EMAIL="icsddevonfwsupport.apps2@capgemini.com"
    - REPO_CONSOLIDATE="devonfw-guide"
    - REPO_DOCGEN="devon-docgen"
    - GH_REPO_CONSOLIDATE="github.com/${ORG}/${REPO_CONSOLIDATE}.git"
    - GH_REPO_DOCGEN="github.com/${ORG}/${REPO_DOCGEN}.git"
    - secure: OmBtP3blxBoLckNQRrN02v0XjHmf1xoyL6qPOOYUyzodVb35Y73bvWXW4+v6FMZSKwlHunADq+TNy6BAqrdRK09rmeL1ErQKz59rOkOg/aZpNb+NE+Hyz/MNotEUZkLCM8lfH+ycLVtmbn3aWEzSzTNYg6/EaZc17YQIR7zZx8GLqGqg1FB6MRdVs8053/u4QwVG9dLhPsha3KPLju3jEZz3+9vCIV2RIslZajLwiXVGww2hBCFXoJZoloaatHdECdIin2HyoQWDK9fzXc81OQh6cQ7/Un0qT2QOCZiExw0J9b8rIpRBDsKnrTiiZ6zae/JaZZH9t1gr4jMmur3CRDhWsjhA8UpmjU5n3hb7o5lPAcPtubE1beJyIKMLbXARKTk03Nbq5qgPa+iRNqtDtUjeQAn1QUeLBx71cgA7kAywd8QzRZJ7DkirTxnGGGRSIyWM9+7JZF0/vcqHtnVKjqRXwdq5m3JxdyEy8sdrbbQJwoMwLb81g5lKWzUzB8bJJAfF0rJ53MddFcjZW6OGh2oLTDZgJ4Xw0NSa3dQYQ2we0sJiz7ttU8ifJ6JtMK/0GIrHS2Z2a0P5fK3pzgQ1vJWTZfkfsgp4U5n+7CaTHcHOiaUcdd4g5EbazoL469bi8iLx/eogH7hWcViTLyeh6u9M8FmL/PnXSzJ1lJQjxtI=
install: true
before_install:
  - cd ..
  - sudo apt-get update
  - sudo apt-get install -y imagemagick
jobs:
  include:
    - stage: Generate PDF
      if: (type = push) AND (commit_message !~ /^PDF devonfw guide \| Travis CI build number.*$/)
      script:
        - git config --global user.email ${EMAIL}
        - git config --global user.name ${USER}
        # Fix PNG images (devonfw-guide already cloned)
        - cd ${REPO_CONSOLIDATE}
        - git checkout master
        - find . -name '*.png' -exec mogrify -interlace none -format png {} +
        - find . -name '*.PNG' -exec mogrify -interlace none -format PNG {} +
        # Generate PDF
        - mvn clean package -Ddocgen.images.dir=images,documentation -Doutput.format=pdf
        - mv ./target/generated-docs/master.pdf ./devonfw_guide.pdf
        # Commit and push new devonfw guide
        - git add ./devonfw_guide.pdf
        - git commit -m "PDF devonfw guide | Travis CI build number $TRAVIS_BUILD_NUMBER"
        - git remote add origin-pdf "https://${USER}:${GITHUB_TOKEN}@${GH_REPO_CONSOLIDATE}"
        - git push origin-pdf master
    - stage: Trigger devonfw.com update
      if: (type = push) AND (commit_message !~ /^PDF devonfw guide \| Travis CI build number.*$/)
      script:
        # Update Website on success
        - git clone https://${USER}:${GITHUB_TOKEN}@github.com/${ORG}/devonfw.github.io.git --recurse-submodules
        - cd devonfw.github.io/${REPO_CONSOLIDATE}
        - git checkout develop
        - git pull
        - cd ..
        - git add ${REPO_CONSOLIDATE}
        - git commit -m "[DocUpdate]"
        - git push origin develop
